// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] icmp_ln191_fu_455_p2;
wire   [0:0] icmp_ln193_fu_491_p2;
wire   [0:0] and_ln239_fu_725_p2;
reg    ap_predicate_op119_read_state1;
reg    ap_predicate_op165_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln191_reg_1058;
reg   [0:0] icmp_ln191_reg_1058_pp0_iter1_reg;
reg   [0:0] icmp_ln193_reg_1062;
reg   [0:0] icmp_ln193_reg_1062_pp0_iter1_reg;
reg   [0:0] icmp_ln209_reg_1066;
reg   [0:0] icmp_ln209_reg_1066_pp0_iter1_reg;
reg    ap_predicate_op233_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
wire    ap_enable_reg_pp0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
wire   [0:0] icmp_ln209_fu_500_p2;
reg   [31:0] grp_load_fu_367_p1;
reg   [31:0] current_block_write_load_1_reg_1070;
wire   [31:0] k_y_1_fu_512_p2;
reg   [31:0] k_y_1_reg_1075;
wire   [6:0] current_line_in_block_fu_550_p2;
reg   [6:0] current_line_in_block_reg_1080;
wire   [31:0] current_block_read_fu_906_p2;
reg   [31:0] current_block_read_reg_1112;
wire   [6:0] inputBuf_V_address0;
reg    inputBuf_V_ce0;
wire   [7:0] inputBuf_V_q0;
reg   [6:0] inputBuf_V_address1;
reg    inputBuf_V_ce1;
reg    inputBuf_V_we1;
wire   [6:0] inputBuf_V_1_address0;
reg    inputBuf_V_1_ce0;
wire   [7:0] inputBuf_V_1_q0;
reg   [6:0] inputBuf_V_1_address1;
reg    inputBuf_V_1_ce1;
reg    inputBuf_V_1_we1;
wire   [6:0] inputBuf_V_2_address0;
reg    inputBuf_V_2_ce0;
wire   [7:0] inputBuf_V_2_q0;
reg   [6:0] inputBuf_V_2_address1;
reg    inputBuf_V_2_ce1;
reg    inputBuf_V_2_we1;
wire   [6:0] inputBuf_V_3_address0;
reg    inputBuf_V_3_ce0;
wire   [7:0] inputBuf_V_3_q0;
reg   [6:0] inputBuf_V_3_address1;
reg    inputBuf_V_3_ce1;
reg    inputBuf_V_3_we1;
wire   [6:0] inputBuf_V_4_address0;
reg    inputBuf_V_4_ce0;
wire   [7:0] inputBuf_V_4_q0;
reg   [6:0] inputBuf_V_4_address1;
reg    inputBuf_V_4_ce1;
reg    inputBuf_V_4_we1;
wire   [6:0] inputBuf_V_5_address0;
reg    inputBuf_V_5_ce0;
wire   [7:0] inputBuf_V_5_q0;
reg   [6:0] inputBuf_V_5_address1;
reg    inputBuf_V_5_ce1;
reg    inputBuf_V_5_we1;
wire   [63:0] zext_ln242_fu_731_p1;
wire   [63:0] zext_ln196_fu_825_p1;
wire   [63:0] zext_ln215_fu_910_p1;
reg   [13:0] i_fu_88;
wire   [13:0] i_2_fu_461_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_i_1;
reg   [31:0] ofm_y_fu_92;
wire   [31:0] ofm_y_2_fu_669_p3;
reg   [31:0] ap_sig_allocacmp_ofm_y_load;
wire   [0:0] icmp_ln218_fu_562_p2;
wire   [0:0] icmp_ln221_fu_582_p2;
wire   [0:0] icmp_ln224_fu_598_p2;
wire   [0:0] icmp_ln227_fu_628_p2;
reg   [31:0] ofm_x_fu_96;
wire   [31:0] ofm_x_1_fu_622_p2;
reg   [31:0] ap_sig_allocacmp_ofm_x_load;
reg   [31:0] ap_sig_allocacmp_ofm_x_load_1;
reg   [31:0] inp_fu_100;
wire   [31:0] inp_2_fu_677_p3;
wire   [31:0] inp_1_fu_839_p2;
reg   [31:0] ap_sig_allocacmp_inp_load;
reg   [31:0] ap_sig_allocacmp_inp_load_2;
reg   [31:0] ap_sig_allocacmp_inp_load_1;
reg   [31:0] grp_load_fu_370_p1;
reg   [31:0] k_y_fu_104;
reg   [31:0] ap_sig_allocacmp_k_y_load;
reg   [31:0] k_x_fu_108;
wire   [31:0] k_x_1_fu_576_p2;
reg   [31:0] ap_sig_allocacmp_k_x_load;
reg   [31:0] ap_sig_allocacmp_k_x_load_1;
reg   [31:0] current_block_write_fu_112;
wire   [31:0] current_block_write_4_fu_774_p3;
wire   [31:0] current_block_write_2_fu_867_p3;
reg   [31:0] ap_sig_allocacmp_current_block_write_load_1;
reg   [31:0] ap_sig_allocacmp_current_block_write_load_3;
reg   [31:0] ap_sig_allocacmp_current_block_write_load_4;
reg   [31:0] ap_sig_allocacmp_current_block_write_load;
reg   [31:0] ap_sig_allocacmp_current_block_write_load_2;
wire   [0:0] grp_fu_391_p2;
reg   [31:0] grp_load_fu_376_p1;
reg   [31:0] read_block_fu_116;
wire   [31:0] read_block_2_fu_756_p2;
wire   [31:0] read_block_1_fu_875_p2;
reg   [31:0] ap_sig_allocacmp_read_block_load_2;
reg   [31:0] ap_sig_allocacmp_read_block_load;
reg   [31:0] ap_sig_allocacmp_read_block_load_1;
reg   [31:0] grp_load_fu_373_p1;
reg   [31:0] count_simd_fu_120;
wire   [31:0] count_simd_1_fu_556_p2;
reg   [31:0] ap_sig_allocacmp_count_simd_load;
reg   [31:0] ap_sig_allocacmp_count_simd_load_1;
reg   [31:0] current_line_fu_124;
wire   [31:0] grp_fu_385_p2;
reg   [31:0] ap_sig_allocacmp_current_line_load_2;
reg   [31:0] ap_sig_allocacmp_current_line_load_3;
reg   [31:0] ap_sig_allocacmp_current_line_load;
reg   [31:0] ap_sig_allocacmp_current_line_load_1;
reg   [31:0] grp_load_fu_379_p1;
reg   [31:0] grp_load_fu_382_p1;
reg   [31:0] counter_internal_block_fu_128;
wire   [31:0] counter_internal_block_2_fu_812_p3;
reg   [31:0] ap_sig_allocacmp_counter_internal_block_load;
reg   [31:0] ap_sig_allocacmp_counter_internal_block_load_1;
reg   [31:0] ap_sig_allocacmp_counter_internal_block_load_2;
wire   [7:0] tmp_fu_936_p8;
wire   [2:0] trunc_ln242_fu_741_p1;
wire   [2:0] trunc_ln196_fu_835_p1;
wire   [5:0] trunc_ln191_2_fu_487_p1;
wire   [5:0] trunc_ln191_1_fu_483_p1;
wire   [5:0] add_ln214_fu_518_p2;
wire   [3:0] trunc_ln214_fu_524_p1;
wire   [6:0] shl_ln_fu_528_p3;
wire   [6:0] shl_ln214_1_fu_536_p3;
wire   [6:0] sub_ln214_fu_544_p2;
wire   [6:0] trunc_ln191_fu_479_p1;
wire   [31:0] ofm_y_1_fu_657_p2;
wire   [0:0] icmp_ln230_fu_663_p2;
wire   [0:0] icmp_ln239_fu_713_p2;
wire   [0:0] icmp_ln239_1_fu_719_p2;
wire   [31:0] current_block_write_3_fu_762_p2;
wire   [0:0] icmp_ln251_fu_768_p2;
wire   [31:0] counter_internal_block_1_fu_800_p2;
wire   [0:0] icmp_ln258_fu_806_p2;
wire   [31:0] current_block_write_1_fu_855_p2;
wire   [0:0] icmp_ln202_fu_861_p2;
wire   [0:0] icmp_ln211_fu_919_p2;
wire   [31:0] add_ln212_fu_924_p2;
wire   [31:0] tmp_fu_936_p7;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0;
reg    ap_predicate_op129_store_state1;
reg    ap_enable_operation_129;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op175_store_state1;
reg    ap_enable_operation_175;
reg    ap_predicate_op221_load_state2;
reg    ap_enable_operation_221;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op230_load_state3;
reg    ap_enable_operation_230;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op131_store_state1;
reg    ap_enable_operation_131;
reg    ap_predicate_op177_store_state1;
reg    ap_enable_operation_177;
reg    ap_predicate_op220_load_state2;
reg    ap_enable_operation_220;
reg    ap_predicate_op229_load_state3;
reg    ap_enable_operation_229;
reg    ap_predicate_op133_store_state1;
reg    ap_enable_operation_133;
reg    ap_predicate_op179_store_state1;
reg    ap_enable_operation_179;
reg    ap_predicate_op219_load_state2;
reg    ap_enable_operation_219;
reg    ap_predicate_op228_load_state3;
reg    ap_enable_operation_228;
reg    ap_predicate_op135_store_state1;
reg    ap_enable_operation_135;
reg    ap_predicate_op181_store_state1;
reg    ap_enable_operation_181;
reg    ap_predicate_op218_load_state2;
reg    ap_enable_operation_218;
reg    ap_predicate_op227_load_state3;
reg    ap_enable_operation_227;
reg    ap_predicate_op137_store_state1;
reg    ap_enable_operation_137;
reg    ap_predicate_op183_store_state1;
reg    ap_enable_operation_183;
reg    ap_predicate_op217_load_state2;
reg    ap_enable_operation_217;
reg    ap_predicate_op226_load_state3;
reg    ap_enable_operation_226;
reg    ap_predicate_op139_store_state1;
reg    ap_enable_operation_139;
reg    ap_predicate_op185_store_state1;
reg    ap_enable_operation_185;
reg    ap_predicate_op222_load_state2;
reg    ap_enable_operation_222;
reg    ap_predicate_op231_load_state3;
reg    ap_enable_operation_231;
wire    ap_start_int;
reg    ap_condition_366;
reg    ap_condition_325;
reg    ap_condition_313;
reg    ap_condition_293;
reg    ap_condition_283;
reg    ap_condition_838;
reg    ap_condition_345;
reg    ap_condition_343;
reg    ap_condition_855;
reg    ap_condition_964;
reg    ap_condition_968;
reg    ap_condition_972;
reg    ap_condition_976;
reg    ap_condition_980;
reg    ap_condition_989;
reg    ap_condition_996;
reg    ap_condition_999;
reg    ap_condition_280;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s_inputBubkb #(
    .DataWidth( 8 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_address0),
    .ce0(inputBuf_V_ce0),
    .q0(inputBuf_V_q0),
    .address1(inputBuf_V_address1),
    .ce1(inputBuf_V_ce1),
    .we1(inputBuf_V_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s_inputBubkb #(
    .DataWidth( 8 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_1_address0),
    .ce0(inputBuf_V_1_ce0),
    .q0(inputBuf_V_1_q0),
    .address1(inputBuf_V_1_address1),
    .ce1(inputBuf_V_1_ce1),
    .we1(inputBuf_V_1_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s_inputBubkb #(
    .DataWidth( 8 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_2_address0),
    .ce0(inputBuf_V_2_ce0),
    .q0(inputBuf_V_2_q0),
    .address1(inputBuf_V_2_address1),
    .ce1(inputBuf_V_2_ce1),
    .we1(inputBuf_V_2_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s_inputBubkb #(
    .DataWidth( 8 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_3_address0),
    .ce0(inputBuf_V_3_ce0),
    .q0(inputBuf_V_3_q0),
    .address1(inputBuf_V_3_address1),
    .ce1(inputBuf_V_3_ce1),
    .we1(inputBuf_V_3_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s_inputBubkb #(
    .DataWidth( 8 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_4_address0),
    .ce0(inputBuf_V_4_ce0),
    .q0(inputBuf_V_4_q0),
    .address1(inputBuf_V_4_address1),
    .ce1(inputBuf_V_4_ce1),
    .we1(inputBuf_V_4_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s_inputBubkb #(
    .DataWidth( 8 ),
    .AddressRange( 84 ),
    .AddressWidth( 7 ))
inputBuf_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_5_address0),
    .ce0(inputBuf_V_5_ce0),
    .q0(inputBuf_V_5_q0),
    .address1(inputBuf_V_5_address1),
    .ce1(inputBuf_V_5_ce1),
    .we1(inputBuf_V_5_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_mux_632_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 32 ),
    .dout_WIDTH( 8 ))
mux_632_8_1_1_U1(
    .din0(inputBuf_V_q0),
    .din1(inputBuf_V_1_q0),
    .din2(inputBuf_V_2_q0),
    .din3(inputBuf_V_3_q0),
    .din4(inputBuf_V_4_q0),
    .din5(inputBuf_V_5_q0),
    .din6(tmp_fu_936_p7),
    .dout(tmp_fu_936_p8)
);

ConvolutionInputGenerator_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_283)) begin
            count_simd_fu_120 <= 32'd0;
        end else if ((1'b1 == ap_condition_293)) begin
            count_simd_fu_120 <= 32'd0;
        end else if ((1'b1 == ap_condition_313)) begin
            count_simd_fu_120 <= 32'd0;
        end else if ((1'b1 == ap_condition_325)) begin
            count_simd_fu_120 <= 32'd0;
        end else if ((1'b1 == ap_condition_366)) begin
            count_simd_fu_120 <= count_simd_1_fu_556_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            count_simd_fu_120 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_345)) begin
            counter_internal_block_fu_128 <= 32'd0;
        end else if (((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0))) begin
            counter_internal_block_fu_128 <= counter_internal_block_2_fu_812_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            counter_internal_block_fu_128 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_345)) begin
            current_block_write_fu_112 <= current_block_write_2_fu_867_p3;
        end else if ((1'b1 == ap_condition_343)) begin
            current_block_write_fu_112 <= current_block_write_4_fu_774_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            current_block_write_fu_112 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_391_p2 == 1'd1))) begin
        current_line_fu_124 <= 32'd0;
    end else if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_391_p2 == 1'd1))) begin
        current_line_fu_124 <= 32'd0;
    end else if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_391_p2 == 1'd0)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_391_p2 == 1'd0)))) begin
        current_line_fu_124 <= grp_fu_385_p2;
    end else if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        current_line_fu_124 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((icmp_ln191_fu_455_p2 == 1'd0)) begin
            i_fu_88 <= i_2_fu_461_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_88 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0))) begin
            inp_fu_100 <= inp_1_fu_839_p2;
        end else if ((1'b1 == ap_condition_283)) begin
            inp_fu_100 <= inp_2_fu_677_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            inp_fu_100 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_283)) begin
            k_x_fu_108 <= 32'd0;
        end else if ((1'b1 == ap_condition_293)) begin
            k_x_fu_108 <= 32'd0;
        end else if ((1'b1 == ap_condition_313)) begin
            k_x_fu_108 <= 32'd0;
        end else if ((1'b1 == ap_condition_325)) begin
            k_x_fu_108 <= k_x_1_fu_576_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_x_fu_108 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_280)) begin
            k_y_fu_104 <= 32'd0;
        end else if ((1'b1 == ap_condition_313)) begin
            k_y_fu_104 <= k_y_1_fu_512_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_y_fu_104 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_283)) begin
            ofm_x_fu_96 <= 32'd0;
        end else if ((1'b1 == ap_condition_293)) begin
            ofm_x_fu_96 <= ofm_x_1_fu_622_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ofm_x_fu_96 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_283)) begin
            ofm_y_fu_92 <= ofm_y_2_fu_669_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ofm_y_fu_92 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_838)) begin
        if ((1'b1 == ap_condition_345)) begin
            read_block_fu_116 <= read_block_1_fu_875_p2;
        end else if ((1'b1 == ap_condition_343)) begin
            read_block_fu_116 <= read_block_2_fu_756_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            read_block_fu_116 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln191_reg_1058 <= icmp_ln191_fu_455_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln209_reg_1066 == 1'd1) & (icmp_ln193_reg_1062 == 1'd0) & (icmp_ln191_reg_1058 == 1'd0))) begin
        current_block_read_reg_1112 <= current_block_read_fu_906_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln209_fu_500_p2 == 1'd1))) begin
        current_block_write_load_1_reg_1070 <= grp_load_fu_367_p1;
        current_line_in_block_reg_1080 <= current_line_in_block_fu_550_p2;
        k_y_1_reg_1075 <= k_y_1_fu_512_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln191_reg_1058_pp0_iter1_reg <= icmp_ln191_reg_1058;
        icmp_ln193_reg_1062_pp0_iter1_reg <= icmp_ln193_reg_1062;
        icmp_ln209_reg_1066_pp0_iter1_reg <= icmp_ln209_reg_1066;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln193_reg_1062 <= icmp_ln193_fu_491_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln209_reg_1066 <= icmp_ln209_fu_500_p2;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln191_fu_455_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_count_simd_load = 32'd0;
    end else begin
        ap_sig_allocacmp_count_simd_load = count_simd_fu_120;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_count_simd_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_count_simd_load_1 = count_simd_fu_120;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_counter_internal_block_load = 32'd0;
    end else begin
        ap_sig_allocacmp_counter_internal_block_load = counter_internal_block_fu_128;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_counter_internal_block_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_counter_internal_block_load_1 = counter_internal_block_fu_128;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_counter_internal_block_load_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_counter_internal_block_load_2 = counter_internal_block_fu_128;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_block_write_load = 32'd0;
    end else begin
        ap_sig_allocacmp_current_block_write_load = current_block_write_fu_112;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_block_write_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_block_write_load_1 = current_block_write_fu_112;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_block_write_load_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_block_write_load_2 = current_block_write_fu_112;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_block_write_load_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_block_write_load_3 = current_block_write_fu_112;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_block_write_load_4 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_block_write_load_4 = current_block_write_fu_112;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load = current_line_fu_124;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_1 = current_line_fu_124;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_2 = current_line_fu_124;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_3 = current_line_fu_124;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 14'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_88;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_inp_load = 32'd0;
    end else begin
        ap_sig_allocacmp_inp_load = inp_fu_100;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_inp_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_inp_load_1 = inp_fu_100;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_inp_load_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_inp_load_2 = inp_fu_100;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_x_load = 32'd0;
    end else begin
        ap_sig_allocacmp_k_x_load = k_x_fu_108;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_x_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_k_x_load_1 = k_x_fu_108;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_y_load = 32'd0;
    end else begin
        ap_sig_allocacmp_k_y_load = k_y_fu_104;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_x_load = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_x_load = ofm_x_fu_96;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_x_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_x_load_1 = ofm_x_fu_96;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_y_load = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_y_load = ofm_y_fu_92;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_read_block_load = 32'd0;
    end else begin
        ap_sig_allocacmp_read_block_load = read_block_fu_116;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_read_block_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_read_block_load_1 = read_block_fu_116;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_read_block_load_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_read_block_load_2 = read_block_fu_116;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if ((icmp_ln193_fu_491_p2 == 1'd1)) begin
            grp_load_fu_367_p1 = ap_sig_allocacmp_current_block_write_load;
        end else if (((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln209_fu_500_p2 == 1'd1))) begin
            grp_load_fu_367_p1 = ap_sig_allocacmp_current_block_write_load_1;
        end else begin
            grp_load_fu_367_p1 = 'bx;
        end
    end else begin
        grp_load_fu_367_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if ((icmp_ln193_fu_491_p2 == 1'd1)) begin
            grp_load_fu_370_p1 = ap_sig_allocacmp_inp_load_1;
        end else if ((1'b1 == ap_condition_964)) begin
            grp_load_fu_370_p1 = ap_sig_allocacmp_inp_load_2;
        end else begin
            grp_load_fu_370_p1 = 'bx;
        end
    end else begin
        grp_load_fu_370_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (grp_fu_391_p2 == 1'd1))) begin
            grp_load_fu_373_p1 = ap_sig_allocacmp_read_block_load_1;
        end else if ((icmp_ln193_fu_491_p2 == 1'd0)) begin
            grp_load_fu_373_p1 = ap_sig_allocacmp_read_block_load_2;
        end else begin
            grp_load_fu_373_p1 = 'bx;
        end
    end else begin
        grp_load_fu_373_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (grp_fu_391_p2 == 1'd1))) begin
            grp_load_fu_376_p1 = ap_sig_allocacmp_current_block_write_load_2;
        end else if (((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0))) begin
            grp_load_fu_376_p1 = ap_sig_allocacmp_current_block_write_load_3;
        end else begin
            grp_load_fu_376_p1 = 'bx;
        end
    end else begin
        grp_load_fu_376_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if ((icmp_ln193_fu_491_p2 == 1'd1)) begin
            grp_load_fu_379_p1 = ap_sig_allocacmp_current_line_load;
        end else if (((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0))) begin
            grp_load_fu_379_p1 = ap_sig_allocacmp_current_line_load_2;
        end else begin
            grp_load_fu_379_p1 = 'bx;
        end
    end else begin
        grp_load_fu_379_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if ((icmp_ln193_fu_491_p2 == 1'd1)) begin
            grp_load_fu_382_p1 = ap_sig_allocacmp_current_line_load_1;
        end else if (((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0))) begin
            grp_load_fu_382_p1 = ap_sig_allocacmp_current_line_load_3;
        end else begin
            grp_load_fu_382_p1 = 'bx;
        end
    end else begin
        grp_load_fu_382_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_start_int == 1'b1) & (ap_predicate_op165_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | ((ap_start_int == 1'b1) & (ap_predicate_op119_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op165_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op119_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (trunc_ln196_fu_835_p1 == 3'd1))) begin
            inputBuf_V_1_address1 = zext_ln196_fu_825_p1;
        end else if ((1'b1 == ap_condition_968)) begin
            inputBuf_V_1_address1 = zext_ln242_fu_731_p1;
        end else begin
            inputBuf_V_1_address1 = 'bx;
        end
    end else begin
        inputBuf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_1_ce0 = 1'b1;
    end else begin
        inputBuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_1_ce1 = 1'b1;
    end else begin
        inputBuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_1_we1 = 1'b1;
    end else begin
        inputBuf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (trunc_ln196_fu_835_p1 == 3'd2))) begin
            inputBuf_V_2_address1 = zext_ln196_fu_825_p1;
        end else if ((1'b1 == ap_condition_972)) begin
            inputBuf_V_2_address1 = zext_ln242_fu_731_p1;
        end else begin
            inputBuf_V_2_address1 = 'bx;
        end
    end else begin
        inputBuf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_2_ce0 = 1'b1;
    end else begin
        inputBuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_2_ce1 = 1'b1;
    end else begin
        inputBuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_2_we1 = 1'b1;
    end else begin
        inputBuf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (trunc_ln196_fu_835_p1 == 3'd3))) begin
            inputBuf_V_3_address1 = zext_ln196_fu_825_p1;
        end else if ((1'b1 == ap_condition_976)) begin
            inputBuf_V_3_address1 = zext_ln242_fu_731_p1;
        end else begin
            inputBuf_V_3_address1 = 'bx;
        end
    end else begin
        inputBuf_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_3_ce0 = 1'b1;
    end else begin
        inputBuf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_3_ce1 = 1'b1;
    end else begin
        inputBuf_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_3_we1 = 1'b1;
    end else begin
        inputBuf_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (trunc_ln196_fu_835_p1 == 3'd4))) begin
            inputBuf_V_4_address1 = zext_ln196_fu_825_p1;
        end else if ((1'b1 == ap_condition_980)) begin
            inputBuf_V_4_address1 = zext_ln242_fu_731_p1;
        end else begin
            inputBuf_V_4_address1 = 'bx;
        end
    end else begin
        inputBuf_V_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_4_ce0 = 1'b1;
    end else begin
        inputBuf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_4_ce1 = 1'b1;
    end else begin
        inputBuf_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_4_we1 = 1'b1;
    end else begin
        inputBuf_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if ((1'b1 == ap_condition_996)) begin
            inputBuf_V_5_address1 = zext_ln196_fu_825_p1;
        end else if ((1'b1 == ap_condition_989)) begin
            inputBuf_V_5_address1 = zext_ln242_fu_731_p1;
        end else begin
            inputBuf_V_5_address1 = 'bx;
        end
    end else begin
        inputBuf_V_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_5_ce0 = 1'b1;
    end else begin
        inputBuf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & ~(trunc_ln196_fu_835_p1 == 3'd0) & ~(trunc_ln196_fu_835_p1 == 3'd1) & ~(trunc_ln196_fu_835_p1 == 3'd2) & ~(trunc_ln196_fu_835_p1 == 3'd3) & ~(trunc_ln196_fu_835_p1 == 3'd4) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & ~(trunc_ln242_fu_741_p1 == 3'd0) & ~(trunc_ln242_fu_741_p1 == 3'd1) & ~(trunc_ln242_fu_741_p1 == 3'd2) & ~(trunc_ln242_fu_741_p1 == 3'd3) & ~(trunc_ln242_fu_741_p1 == 3'd4) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_5_ce1 = 1'b1;
    end else begin
        inputBuf_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & ~(trunc_ln196_fu_835_p1 == 3'd0) & ~(trunc_ln196_fu_835_p1 == 3'd1) & ~(trunc_ln196_fu_835_p1 == 3'd2) & ~(trunc_ln196_fu_835_p1 == 3'd3) & ~(trunc_ln196_fu_835_p1 == 3'd4) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & ~(trunc_ln242_fu_741_p1 == 3'd0) & ~(trunc_ln242_fu_741_p1 == 3'd1) & ~(trunc_ln242_fu_741_p1 == 3'd2) & ~(trunc_ln242_fu_741_p1 == 3'd3) & ~(trunc_ln242_fu_741_p1 == 3'd4) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_5_we1 = 1'b1;
    end else begin
        inputBuf_V_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_855)) begin
        if (((icmp_ln193_fu_491_p2 == 1'd1) & (trunc_ln196_fu_835_p1 == 3'd0))) begin
            inputBuf_V_address1 = zext_ln196_fu_825_p1;
        end else if ((1'b1 == ap_condition_999)) begin
            inputBuf_V_address1 = zext_ln242_fu_731_p1;
        end else begin
            inputBuf_V_address1 = 'bx;
        end
    end else begin
        inputBuf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_ce0 = 1'b1;
    end else begin
        inputBuf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_ce1 = 1'b1;
    end else begin
        inputBuf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        inputBuf_V_we1 = 1'b1;
    end else begin
        inputBuf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op233_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_predicate_op233_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if (((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln212_fu_924_p2 = ($signed(current_block_read_reg_1112) + $signed(32'd4294967290));

assign add_ln214_fu_518_p2 = (trunc_ln191_2_fu_487_p1 + trunc_ln191_1_fu_483_p1);

assign and_ln239_fu_725_p2 = (icmp_ln239_fu_713_p2 & icmp_ln239_1_fu_719_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_iter0_fsm_state1 == ap_CS_iter0_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b0) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_280 = ((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (icmp_ln224_fu_598_p2 == 1'd1) & (icmp_ln221_fu_582_p2 == 1'd1) & (icmp_ln218_fu_562_p2 == 1'd1) & (icmp_ln209_fu_500_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_283 = ((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (icmp_ln227_fu_628_p2 == 1'd1) & (icmp_ln224_fu_598_p2 == 1'd1) & (icmp_ln221_fu_582_p2 == 1'd1) & (icmp_ln218_fu_562_p2 == 1'd1) & (icmp_ln209_fu_500_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_293 = ((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (icmp_ln227_fu_628_p2 == 1'd0) & (icmp_ln224_fu_598_p2 == 1'd1) & (icmp_ln221_fu_582_p2 == 1'd1) & (icmp_ln218_fu_562_p2 == 1'd1) & (icmp_ln209_fu_500_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_313 = ((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (icmp_ln224_fu_598_p2 == 1'd0) & (icmp_ln221_fu_582_p2 == 1'd1) & (icmp_ln218_fu_562_p2 == 1'd1) & (icmp_ln209_fu_500_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_325 = ((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (icmp_ln221_fu_582_p2 == 1'd0) & (icmp_ln218_fu_562_p2 == 1'd1) & (icmp_ln209_fu_500_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_343 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (grp_fu_391_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_345 = ((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (grp_fu_391_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_366 = ((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (icmp_ln218_fu_562_p2 == 1'd0) & (icmp_ln209_fu_500_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_838 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op233_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_predicate_op165_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op119_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_855 = ((ap_start_int == 1'b1) & (icmp_ln191_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_964 = ((icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln227_fu_628_p2 == 1'd1) & (icmp_ln224_fu_598_p2 == 1'd1) & (icmp_ln221_fu_582_p2 == 1'd1) & (icmp_ln218_fu_562_p2 == 1'd1) & (icmp_ln209_fu_500_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_968 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd1));
end

always @ (*) begin
    ap_condition_972 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd2));
end

always @ (*) begin
    ap_condition_976 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd3));
end

always @ (*) begin
    ap_condition_980 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd4));
end

always @ (*) begin
    ap_condition_989 = (~(trunc_ln242_fu_741_p1 == 3'd0) & ~(trunc_ln242_fu_741_p1 == 3'd1) & ~(trunc_ln242_fu_741_p1 == 3'd2) & ~(trunc_ln242_fu_741_p1 == 3'd3) & ~(trunc_ln242_fu_741_p1 == 3'd4) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_996 = (~(trunc_ln196_fu_835_p1 == 3'd0) & ~(trunc_ln196_fu_835_p1 == 3'd1) & ~(trunc_ln196_fu_835_p1 == 3'd2) & ~(trunc_ln196_fu_835_p1 == 3'd3) & ~(trunc_ln196_fu_835_p1 == 3'd4) & (icmp_ln193_fu_491_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_999 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd0));
end

always @ (*) begin
    ap_enable_operation_129 = (ap_predicate_op129_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_131 = (ap_predicate_op131_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_133 = (ap_predicate_op133_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_135 = (ap_predicate_op135_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_137 = (ap_predicate_op137_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_139 = (ap_predicate_op139_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_175 = (ap_predicate_op175_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_177 = (ap_predicate_op177_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_179 = (ap_predicate_op179_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_181 = (ap_predicate_op181_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_183 = (ap_predicate_op183_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_185 = (ap_predicate_op185_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_217 = (ap_predicate_op217_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_218 = (ap_predicate_op218_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_219 = (ap_predicate_op219_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_220 = (ap_predicate_op220_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_221 = (ap_predicate_op221_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_222 = (ap_predicate_op222_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_226 = (ap_predicate_op226_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_227 = (ap_predicate_op227_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_228 = (ap_predicate_op228_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_229 = (ap_predicate_op229_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_230 = (ap_predicate_op230_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_231 = (ap_predicate_op231_load_state3 == 1'b1);
end

assign ap_enable_reg_pp0_iter0 = 1'b0;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op119_read_state1 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op129_store_state1 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd4));
end

always @ (*) begin
    ap_predicate_op131_store_state1 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd3));
end

always @ (*) begin
    ap_predicate_op133_store_state1 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd2));
end

always @ (*) begin
    ap_predicate_op135_store_state1 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd1));
end

always @ (*) begin
    ap_predicate_op137_store_state1 = ((1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln242_fu_741_p1 == 3'd0));
end

always @ (*) begin
    ap_predicate_op139_store_state1 = (~(trunc_ln242_fu_741_p1 == 3'd0) & ~(trunc_ln242_fu_741_p1 == 3'd1) & ~(trunc_ln242_fu_741_p1 == 3'd2) & ~(trunc_ln242_fu_741_p1 == 3'd3) & ~(trunc_ln242_fu_741_p1 == 3'd4) & (1'd1 == and_ln239_fu_725_p2) & (icmp_ln193_fu_491_p2 == 1'd0) & (icmp_ln191_fu_455_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op165_read_state1 = ((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op175_store_state1 = ((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd4));
end

always @ (*) begin
    ap_predicate_op177_store_state1 = ((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd3));
end

always @ (*) begin
    ap_predicate_op179_store_state1 = ((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd2));
end

always @ (*) begin
    ap_predicate_op181_store_state1 = ((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd1));
end

always @ (*) begin
    ap_predicate_op183_store_state1 = ((icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0) & (trunc_ln196_fu_835_p1 == 3'd0));
end

always @ (*) begin
    ap_predicate_op185_store_state1 = (~(trunc_ln196_fu_835_p1 == 3'd0) & ~(trunc_ln196_fu_835_p1 == 3'd1) & ~(trunc_ln196_fu_835_p1 == 3'd2) & ~(trunc_ln196_fu_835_p1 == 3'd3) & ~(trunc_ln196_fu_835_p1 == 3'd4) & (icmp_ln193_fu_491_p2 == 1'd1) & (icmp_ln191_fu_455_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op217_load_state2 = ((icmp_ln209_reg_1066 == 1'd1) & (icmp_ln193_reg_1062 == 1'd0) & (icmp_ln191_reg_1058 == 1'd0));
end

always @ (*) begin
    ap_predicate_op218_load_state2 = ((icmp_ln209_reg_1066 == 1'd1) & (icmp_ln193_reg_1062 == 1'd0) & (icmp_ln191_reg_1058 == 1'd0));
end

always @ (*) begin
    ap_predicate_op219_load_state2 = ((icmp_ln209_reg_1066 == 1'd1) & (icmp_ln193_reg_1062 == 1'd0) & (icmp_ln191_reg_1058 == 1'd0));
end

always @ (*) begin
    ap_predicate_op220_load_state2 = ((icmp_ln209_reg_1066 == 1'd1) & (icmp_ln193_reg_1062 == 1'd0) & (icmp_ln191_reg_1058 == 1'd0));
end

always @ (*) begin
    ap_predicate_op221_load_state2 = ((icmp_ln209_reg_1066 == 1'd1) & (icmp_ln193_reg_1062 == 1'd0) & (icmp_ln191_reg_1058 == 1'd0));
end

always @ (*) begin
    ap_predicate_op222_load_state2 = ((icmp_ln209_reg_1066 == 1'd1) & (icmp_ln193_reg_1062 == 1'd0) & (icmp_ln191_reg_1058 == 1'd0));
end

always @ (*) begin
    ap_predicate_op226_load_state3 = ((icmp_ln209_reg_1066_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1062_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op227_load_state3 = ((icmp_ln209_reg_1066_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1062_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op228_load_state3 = ((icmp_ln209_reg_1066_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1062_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op229_load_state3 = ((icmp_ln209_reg_1066_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1062_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op230_load_state3 = ((icmp_ln209_reg_1066_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1062_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op231_load_state3 = ((icmp_ln209_reg_1066_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1062_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op233_write_state3 = ((icmp_ln209_reg_1066_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1062_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1058_pp0_iter1_reg == 1'd0));
end

assign count_simd_1_fu_556_p2 = (ap_sig_allocacmp_count_simd_load_1 + 32'd1);

assign counter_internal_block_1_fu_800_p2 = (ap_sig_allocacmp_counter_internal_block_load_2 + 32'd1);

assign counter_internal_block_2_fu_812_p3 = ((icmp_ln258_fu_806_p2[0:0] == 1'b1) ? 32'd0 : counter_internal_block_1_fu_800_p2);

assign current_block_read_fu_906_p2 = (current_block_write_load_1_reg_1070 + k_y_1_reg_1075);

assign current_block_write_1_fu_855_p2 = (grp_load_fu_376_p1 + 32'd1);

assign current_block_write_2_fu_867_p3 = ((icmp_ln202_fu_861_p2[0:0] == 1'b1) ? 32'd0 : current_block_write_1_fu_855_p2);

assign current_block_write_3_fu_762_p2 = (ap_sig_allocacmp_current_block_write_load_4 + 32'd1);

assign current_block_write_4_fu_774_p3 = ((icmp_ln251_fu_768_p2[0:0] == 1'b1) ? 32'd0 : current_block_write_3_fu_762_p2);

assign current_line_in_block_fu_550_p2 = (sub_ln214_fu_544_p2 + trunc_ln191_fu_479_p1);

assign grp_fu_385_p2 = (grp_load_fu_382_p1 + 32'd1);

assign grp_fu_391_p2 = ((grp_fu_385_p2 == 32'd84) ? 1'b1 : 1'b0);

assign i_2_fu_461_p2 = (ap_sig_allocacmp_i_1 + 14'd1);

assign icmp_ln191_fu_455_p2 = ((ap_sig_allocacmp_i_1 == 14'd15420) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_491_p2 = ((ap_sig_allocacmp_inp_load < 32'd420) ? 1'b1 : 1'b0);

assign icmp_ln202_fu_861_p2 = ((current_block_write_1_fu_855_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln209_fu_500_p2 = ((ap_sig_allocacmp_counter_internal_block_load < 32'd1499) ? 1'b1 : 1'b0);

assign icmp_ln211_fu_919_p2 = ((current_block_read_reg_1112 > 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln218_fu_562_p2 = ((count_simd_1_fu_556_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln221_fu_582_p2 = ((k_x_1_fu_576_p2 == 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_598_p2 = ((k_y_1_fu_512_p2 == 32'd5) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_628_p2 = ((ofm_x_1_fu_622_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_663_p2 = ((ofm_y_1_fu_657_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln239_1_fu_719_p2 = ((grp_load_fu_373_p1 < 32'd14) ? 1'b1 : 1'b0);

assign icmp_ln239_fu_713_p2 = ((ap_sig_allocacmp_counter_internal_block_load_1 < 32'd83) ? 1'b1 : 1'b0);

assign icmp_ln251_fu_768_p2 = ((current_block_write_3_fu_762_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_806_p2 = ((counter_internal_block_1_fu_800_p2 == 32'd1499) ? 1'b1 : 1'b0);

assign inp_1_fu_839_p2 = (grp_load_fu_370_p1 + 32'd1);

assign inp_2_fu_677_p3 = ((icmp_ln230_fu_663_p2[0:0] == 1'b1) ? 32'd0 : grp_load_fu_370_p1);

assign inputBuf_V_1_address0 = zext_ln215_fu_910_p1;

assign inputBuf_V_2_address0 = zext_ln215_fu_910_p1;

assign inputBuf_V_3_address0 = zext_ln215_fu_910_p1;

assign inputBuf_V_4_address0 = zext_ln215_fu_910_p1;

assign inputBuf_V_5_address0 = zext_ln215_fu_910_p1;

assign inputBuf_V_address0 = zext_ln215_fu_910_p1;

assign k_x_1_fu_576_p2 = (ap_sig_allocacmp_k_x_load_1 + 32'd1);

assign k_y_1_fu_512_p2 = (ap_sig_allocacmp_k_y_load + 32'd1);

assign ofm_x_1_fu_622_p2 = (ap_sig_allocacmp_ofm_x_load_1 + 32'd1);

assign ofm_y_1_fu_657_p2 = (ap_sig_allocacmp_ofm_y_load + 32'd1);

assign ofm_y_2_fu_669_p3 = ((icmp_ln230_fu_663_p2[0:0] == 1'b1) ? 32'd0 : ofm_y_1_fu_657_p2);

assign out_V_TDATA = tmp_fu_936_p8;

assign read_block_1_fu_875_p2 = (grp_load_fu_373_p1 + 32'd1);

assign read_block_2_fu_756_p2 = (ap_sig_allocacmp_read_block_load + 32'd1);

assign shl_ln214_1_fu_536_p3 = {{add_ln214_fu_518_p2}, {1'd0}};

assign shl_ln_fu_528_p3 = {{trunc_ln214_fu_524_p1}, {3'd0}};

assign sub_ln214_fu_544_p2 = (shl_ln_fu_528_p3 - shl_ln214_1_fu_536_p3);

assign tmp_fu_936_p7 = ((icmp_ln211_fu_919_p2[0:0] == 1'b1) ? add_ln212_fu_924_p2 : current_block_read_reg_1112);

assign trunc_ln191_1_fu_483_p1 = ap_sig_allocacmp_k_x_load[5:0];

assign trunc_ln191_2_fu_487_p1 = ap_sig_allocacmp_ofm_x_load[5:0];

assign trunc_ln191_fu_479_p1 = ap_sig_allocacmp_count_simd_load[6:0];

assign trunc_ln196_fu_835_p1 = grp_load_fu_367_p1[2:0];

assign trunc_ln214_fu_524_p1 = add_ln214_fu_518_p2[3:0];

assign trunc_ln242_fu_741_p1 = grp_load_fu_376_p1[2:0];

assign zext_ln196_fu_825_p1 = grp_load_fu_379_p1;

assign zext_ln215_fu_910_p1 = current_line_in_block_reg_1080;

assign zext_ln242_fu_731_p1 = grp_load_fu_379_p1;

always @ (posedge ap_clk) begin
    ap_enable_reg_pp0_iter1 <= 1'b0;
    ap_enable_reg_pp0_iter2 <= 1'b0;
end

endmodule //ConvolutionInputGenerator_1_ConvolutionInputGenerator_5u_6u_8u_14u_10u_1u_1u_ap_resource_lutram_s
